version: '3.8'

services: 
  postgres: 
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: product_management

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'
